<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #000000;
        width:  100%;
        height: 800px;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to my Blog</span></h1>

    <h3>Test Blog Project</h3>

    <div id="more-information">
        <p>Author: Raphael Gütlin</p>
		<p><a href="mailto:rguetlin@msn.com">rguetlin@msn.com</a></p>
    </div>
	
</div>